#1. Data Loading from TMDB API <a id="1-data-loading" name="1-data-loading"></a>

**To collect the data using this API, I created a loop across 250 pages (20 movies per page = 5,000 movies), making a call for each page. I used time.sleep(0.26) to pause for 0.26 seconds between requests in order to comply with the TMDB rate limit of 40 requests per 10 seconds.**

In [ ]:

# DATA LOADING :
# Source : TMDB API — https://api.themoviedb.org/3
# API Key :
# Fetched using : /movie/popular, /movie/top_rated, /discover/movie, /movie/{id}, /movie/{id}/credits
# Total: 5,500 movies with full metadata


TMDB_API_KEY = ""
TMDB_BASE    = "https://api.themoviedb.org/3"
TMDB_IMG     = "https://image.tmdb.org/t/p/w500"

# How the data was fetched (reference code):
# import requests, time
# for page in range(1, 251) :
#     r = requests.get(f"{TMDB_BASE}/movie/popular",
#                      params={"api_key": TMDB_API_KEY, "page": page})
#     movies += r.json()["results"]
#     time.sleep(0.26)  # TMDB rate limit: 40 req / 10 sec

In [ ]:
def find_data(filename):
    for p in[f"../data/{filename}",f"data/{filename}",f"./{filename}"]:
        if os.path.exists(p):
            return p
        raise FileNotFoundError(filename)

print("Loading TMDB dataset fetched from API \n")

df_raw=pd.read_csv(find_data("tmdb_movies_raw.csv"))
print(f"\n{'='*50 }")
print(f"TMDB DATASET LOADED")
print(f"{'='*50} \n")
print(f"    Rows    : {len(df_raw):,}") # nb lignes
print(f"    Columns : {len(df_raw.columns)}") # nb cols
print(f"    Source  : TMDB API (api.themoviedb.org/3)")
print(f"\n  Columns : {df_raw.columns.tolist()}")

Loading TMDB dataset fetched from API


==================================================
TMDB DATASET LOADED
==================================================
    Rows:    5,500
    Columns: 28
    Source:  TMDB API (api.themoviedb.org/3)

  Columns: ['id', 'imdb_id', 'title', 'original_title', 'original_language', 'overview', 'tagline', 'genres', 'release_date', 'runtime', 'budget', 'revenue', 'popularity', 'vote_average', 'vote_count', 'status', 'adult', 'video', 'homepage', 'poster_path', 'backdrop_path', 'production_companies_name', 'production_companies_country', 'production_countries', 'spoken_languages', 'director', 'writer', 'cast']

In [ ]:
print(" First rows from TMDB API : \n")
# for better visualization, we use the display function
# display (a better function than print that displays an HTML-formatted DataFrame in Jupyter / VS Code)
display(df_raw.head())
print(f"\n Data Type:")
display(df_raw.dtypes.to_frame("dtype")) # returns the column data types and converts them into a dataframe with a dtype column

 First ( rows from TMDB API:

,id,imdb_id,title,original_title,original_language,overview,tagline,genres,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,adult,video,homepage,poster_path,backdrop_path,production_companies_name,production_companies_country,production_countries,spoken_languages,director,writer,cast
0,11,tt0076759,Star Wars,Star Wars,en,Princess Leia is captured and held hostage by ...,"A long time ago in a galaxy far, far away...","Adventure,Action,Science Fiction",1977-05-25,121,11000000,775398007,22.71,8.20,22179,Released,False,False,http://www.starwars.com/films/star-wars-episod...,https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJj...,https://image.tmdb.org/t/p/w500/yUiXA68FfQeA8c...,"Lucasfilm Ltd.,20th Century Fox","US,US",United States of America,English,George Lucas,George Lucas,"Mark Hamill,Harrison Ford,Carrie Fisher,Peter ..."
1,12,tt0266543,Finding Nemo,Finding Nemo,en,"Nemo, an adventurous young clownfish, is unexp...",There are 3.7 trillion fish in the ocean. They...,"Animation,Family,Adventure",2003-05-30,100,94000000,940335536,18.92,7.82,20443,Released,False,False,http://movies.disney.com/finding-nemo,https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1md...,https://image.tmdb.org/t/p/w500/eCynaAOgYYiw5y...,Pixar,US,United States of America,English,Andrew Stanton,Andrew Stanton,"Albert Brooks,Ellen DeGeneres,Alexander Gould,..."
2,13,tt0109830,Forrest Gump,Forrest Gump,en,A man with a low IQ has accomplished great thi...,The world will never be the same once you've s...,"Comedy,Drama,Romance",1994-06-23,142,55000000,677387716,26.63,8.46,29561,Released,False,False,https://www.paramountmovies.com/movies/forrest...,https://image.tmdb.org/t/p/w500/saHP97rTPS5eLm...,https://image.tmdb.org/t/p/w500/67HggiWaP9ZLv5...,"Paramount Pictures,The Steve Tisch Company,Wen...","US,US,US",United States of America,English,Robert Zemeckis,Eric Roth,"Tom Hanks,Robin Wright,Gary Sinise,Sally Field..."
3,14,tt0169547,American Beauty,American Beauty,en,"Lester Burnham, a depressed suburban father in...",... look closer,Drama,1999-09-15,122,15000000,356296601,10.42,8.00,12963,Released,False,False,NaN,https://image.tmdb.org/t/p/w500/wby9315QzVKdW9...,https://image.tmdb.org/t/p/w500/2ndw55F40IkALz...,"DreamWorks Pictures,Jinks/Cohen Company","US,US",United States of America,English,Sam Mendes,Alan Ball,"Kevin Spacey,Annette Bening,Thora Birch,Wes Be..."
4,15,tt0033467,Citizen Kane,Citizen Kane,en,Newspaper magnate Charles Foster Kane is taken...,Some called him a hero...others called him a h...,"Mystery,Drama",1941-04-17,119,839727,23218000,6.36,7.98,6007,Released,False,False,NaN,https://image.tmdb.org/t/p/w500/sav0jxhqiH0bPr...,https://image.tmdb.org/t/p/w500/9Y85oA1y6toL2O...,"Mercury Productions,RKO Radio Pictures",",US",United States of America,English,Orson Welles,Orson Welles,"Orson Welles,Joseph Cotten,Dorothy Comingore,R..."

 Data Type:

                                dtype
id                              int64
imdb_id                           str
title                             str
original_title                    str
original_language                 str
overview                          str
tagline                           str
genres                            str
release_date                      str
runtime                         int64
budget                          int64
revenue                         int64
popularity                    float64
vote_average                  float64
vote_count                      int64
status                            str
adult                            bool
video                            bool
homepage                          str
poster_path                       str
backdrop_path                     str
production_companies_name         str
production_companies_country      str
production_countries              str
spoken_languages                  str
director                          str
writer                            str
cast                              str

**In this step :**

I wanted to understand my data to have a reference throughout the project by documenting my columns. I created a documentation dictionary ("Data Dictionary") named tmdb_schema, where the column name serves as the key (id) and the column description serves as the value (imdb_id).

I grouped my columns to better understand them :

**Identifiers :**

id and imdb_id (an ID number used to cross-reference with other databases)

**General information :**

title, original_title, original_language, overview, tagline, status, adult

**Creative content :**

genres, director, writer, cast (these always come from a separate "credits" endpoint)

**Dates and duration :**

release_date, runtime

**Financial data :**

budget and revenue (both columns are important for calculating ROI / return on investment)

**Popularity and ratings :**

popularity, vote_average, vote_count (the number of votes)

**Images :**

poster_path : the poster image URL combined with TMDB_IMG

backdrop_path : the background image URL (movie scene) used to display the poster

TMDB_IMG+poster_path=https://image.tmdb.org/t/p/w500/xxxx.jpg        

**Production :**

production_compagnies_name, production_compagnies_country production_countries, spoken_languages

In [ ]:
# TMDB API field documentation based on the official API PDF documentation page 6
tmdb_schema = {
"id":                           "TMDB unique identifier",
"imdb_id":                      "IMDb identifier ", # (allows cross-referencing with other databases)
"title":                        "Film title ",
"original_title":               "Title in original language",
"original_language":            "Language code (en, fr, ...)",
"overview":                     "Plot summary", # movie summary important for the recommendation engine
"tagline":                      "Marketing tagline", # Marketing slogan
"genres":                       "Genre(s), comma-separated", # genres are separated by commas
"release_date":                 "YYYY-MM-DD release date", # format YYYY-MM-DD
"runtime":                      "Duration in minutes", # duration in minutes
"budget":                       "Production budget (USD)", # Production budget in USD
"revenue":                      "Box office revenue (USD)", # box office revenue in USD
"popularity":                   "TMDB popularity score", # TMDB popularity score calculated in real-time by TMDB
"vote_average":                 "Average user rating (0-10)", # average rating out of 10
"vote_count":                   "Number of user ratings", # important for rating reliability
"status":                       "Released / In Production / ...", # Movie status
"adult":                        "Adult content flag", # adult content
"poster_path":                  "Full poster image URL", # Movie poster URL (TMDB_IMG)
"backdrop_path":                "Full backdrop image URL", # Background image URL (movie scene) both used to display a poster
"production_companies_name":    "Studio names", # Studio names
"production_companies_country": "Studio countries", # Studio countries
"production_countries":         "Countries of production", # countries where the movie was filmed
"spoken_languages":             "Languages spoken in film", # languages spoken in the movie
"director":                     "Director name (from /credits)", # director name retrieved via /credits
"writer":                       "Writer name (from /credits)", # Writer name retrieved via /credits
"cast":                         "Top 8 cast members (from /credits)", # top 8 principal actors retrieved via /credits
}

# created a dataframe that converts the dictionary into a list of tuples using "list()"
# extracted key and value from the dictionary using the .items() method
# named the dataframe columns "Field" and "Description"
schema_df = pd.DataFrame(list(tmdb_schema.items()), columns=["Field","Description"])
print("TMDB API Schema (PDF page 6):")
display(schema_df)

TMDB API Schema (PDF page 6):

                           Field                         Description
0                             id              TMDB unique identifier
1                        imdb_id                    IMDb identifier
2                          title                         Film title
3                 original_title          Title in original language
4              original_language         Language code (en, fr, ...)
5                       overview                        Plot summary
6                        tagline                   Marketing tagline
7                         genres           Genre(s), comma-separated
8                   release_date             YYYY-MM-DD release date
9                        runtime                 Duration in minutes
10                        budget             Production budget (USD)
11                       revenue            Box office revenue (USD)
12                    popularity               TMDB popularity score
13                  vote_average          Average user rating (0-10)
14                    vote_count              Number of user ratings
15                        status      Released / In Production / ...
16                         adult                  Adult content flag
17                   poster_path               Full poster image URL
18                 backdrop_path             Full backdrop image URL
19     production_companies_name                        Studio names
20  production_companies_country                    Studio countries
21          production_countries             Countries of production
22              spoken_languages            Languages spoken in film
23                      director       Director name (from /credits)
24                        writer         Writer name (from /credits)
25                          cast  Top 8 cast members (from /credits)